### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [isuPatches/WiseFy#111]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by isuPatches** [comment]
Hey @mansya, I am interested!  Can I see 4 without the black border and just the lighter background color instead of two-toned?  

Also, please tell me how I can credit you in the README for the project for the icon.  Thank you so much!

If it's possible for you to provide SVG files for the background and foreground, and a combined SVG, I will gladly use this for the icon on the sample app for WiseFy as well...I'm currently rewriting it in Kotlin.

I always refer to these specs for Android iconography:

- https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
- https://material.io/design/iconography/#grid-keyline-shapes
- http://iconhandbook.co.uk/reference/chart/android/

I really appreciate your effort.

**Comment by isuPatches** [comment]
4 would be lovely!

**Comment by mansya** [comment]
I have uploaded all files to this [**drive**](https://drive.google.com/open?id=1ZpXStoU-XEpCN9taeIUCXa1jGiAriUjI). and I have also submitted you [**Pull Request**](https://github.com/isuPatches/WiseFy/pull/112). please check. but I'm a little confused. I don't know which one to upload the logo to the folder. tell me about this.

**Comment by mansya** [comment]
I really haven't seen pull requests like this before. this my email. mansyaprime93@gmail.com. can we exchange emails ?

**Comment by isuPatches** [comment]
Sure!  My email is isuPatches@yahoo.com

**Comment by isuPatches** [comment]
I have added credit for you to the Readme!  Thanks for reaching out and doing this.  Looks great.

**Comment by isuPatches** [comment]
@mansya I would like to use adaptive icons for the sample app.  https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

For that to be possible, I would need your help.  For these icons with Android:

- The foreground and background color would need to be separate SVGs
- Both layers should be sized at 108 x 108 dp
- The inner 72 x 72 dp of the icon appears within the masked viewport

The PNGs will work for legacy launcher icons, but it would be nice to support Android O and higher.

**Comment by mansya** [comment]
ok. I will do that. you can wait for her miss

**Comment by isuPatches** [comment]
Of course!  No rush at all :)  Thanks again for everything!
