### ISSUE TITLE
Problem adding and connecting to a network when mobile network is enabled

### ISSUE THREAD

**Issue by dariopellegrini** [isuPatches/WiseFy#131]
I'm executing the following code:
```kotlin
GlobalScope.async(Dispatchers.IO) {
            val wisefyReturnCode = wiseFy.addWPA2Network(ssid, password)
            val result = wiseFy.connectToNetwork(ssid, Constants.WIFI_CONNECTION_TIMEOUT)
            Log.i("WifiViewModel", "$wisefyReturnCode and $result")
        }.await()
```

I'm trying with 2 different SSID combinations:
1. Correct SSID and password
2. Wrong SSID and password

When the device has mobile network data switched on I have
```kotlin
wiseFyReturnCode = -1002
result =true
```
for both combinations (1 and 2). This is wrong cause combination 2 should return result = false.

Switching off mobile data instead I have:
```kotlin
// 1. Correct SSID and password
wiseFyReturnCode = -1002
result = true

// 2. Wrong SSID and password
wiseFyReturnCode = -1002
result = false
```
that is completely correct.

Value of wiseFyReturnCode is -1002 probably because it was already added (52 otherwise).

I think that I'm missing something or maybe there is a bug when mobile network data is on.

Can you help?

Thank you.

**Comment by isuPatches** [comment]
Hey there. 

Thanks for the issue.  This is actually by design. 

The result from `addWPA2Network` is only whether the network was added to the saved configurations on the Android device, NOT if we can successfully connect to that network with a given SSID and password combination.

Here's some of the underlying logic and why you're hitting that specific code:

`const val NETWORK_ALREADY_CONFIGURED: Int = -1002`

```kotlin
private fun checkAddNetworkPrerequisites(ssid: String?, password: String?): PrecheckResult =
        when {
            ssid.isNullOrEmpty() || password.isNullOrEmpty() -> {
                PrecheckResult(code = MISSING_PARAMETER)
            }
            wisefySearch.isNetworkASavedConfiguration(ssid) -> {
                PrecheckResult(code = NETWORK_ALREADY_CONFIGURED)
            }
            else -> DEFAULT_PRECHECK_RESULT
}
```

So, as demonstrated above, this will only fail if we're missing a parameter or if you've already stored the network via calling this method before.

If you are changing a network you would need to remove it first and re-add with the updated password.  There currently isn't a nice way to "update" a password for a saved configuration although that would be a sweet feature add for 4.x after it is released.

Here's some additional methods to look at.

For checking connection via the sync API:

```kotlin
fun connectToNetwork(ssidToConnectTo: String?, timeoutInMillis: Int): Boolean
```

For checking connection via the async API:

```kotlin
override fun connectToNetwork(
        ssidToConnectTo: String?,
        timeoutInMillis: Int,
        callbacks: ConnectToNetworkCallbacks?
)
```

For removing a network configuration via the async API:

```kotlin
fun removeNetwork(ssidToRemove: String?): Boolean 
```

For removing a network configuration via the async API:

```kotlin
fun removeNetwork(ssidToRemove: String?, callbacks: RemoveNetworkCallbacks?)
```

I hope this helps and thank you for using this library!

**Comment by isuPatches** [comment]
Ooohh!! Apologies. I see you are using `connectToNetwork` already.  I bet that the issue is missing the `removeNetwork` call inbetween combination changes...sorry!  Did not mean any offense by potentially over-explaining :)

**Comment by isuPatches** [comment]
@dariopellegrini Any update on this?  Did removing and then adding work for you?

**Comment by dariopellegrini** [comment]
@isuPatches thanks for your response. Please keep it paused til Monday. I'll check it out on site and then let you know. Very thank you.

**Comment by isuPatches** [comment]
Please reopen if the suggested method above does not help.

**Comment by dariopellegrini** [comment]
I'm sorry but I have to reopen this.

My target is not changing WiFi network, but check if a WiFi connection is successful while the device is connected to a Mobile network.

The problem is that if I try to add and connect to a WiFi with a wrong password while the device is connected to mobile network, wiseFy.connectToNetwork always gives true as result.

I was busy on another project. I promise I'll be more responsive from now on :D

Thank you.

**Comment by isuPatches** [comment]
`connectToNetwork` uses `isCurrentNetworkConnectedToSSID`.

The requirements for a successful connection are:

1. The device is connected (defined by `isConnected` and `isAvailable` from `NetworkInfo`)
2. The current SSID (defined by `wifiManager.connectionInfo.ssid`) matches the SSID provided

If you are getting a -1002 (meaning that the network has already been added) that is suspicious of a bug on the client side.

WiseFy does not clear the network configuration on a network add (by design), so there's a good chance that you already have this stored network configuration and may even be using it at the time of the second run.

As mentioned above, I would recommend calling `removeNetwork` and changing the logic to this:

```
GlobalScope.async(Dispatchers.IO) {
            val networkRemoved = wiseFy.removeNetwork(ssid)
            val wisefyReturnCode = wiseFy.addWPA2Network(ssid, password)
            val result = wiseFy.connectToNetwork(ssid, Constants.WIFI_CONNECTION_TIMEOUT)
            Log.i("WifiViewModel", "$wisefyReturnCode and $result")
        }.await()
```

especially for multiple runs.  What I'm suspecting is happening is this flow:

1. Network is added
2. Network is enabled and connection checked 
3  Network is attempted to be re-added with incorrrect password but fails because already exists
4. Network is re-enabled and connection re-checked

The mobile network connection is not a factor as the SSID is used to verify the connection.
